version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: ./backend
    container_name: backend_container
    ports:
      - "9900:9900"
    environment:
      - REDIS_HOST=redis
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3901:3000"
    depends_on:
      - app
    restart: always
